### ISSUE TITLE
Buffer is empty (react-native)

### ISSUE THREAD

**Issue by RafaelCENG** [markw65/fit-file-writer#1]
Is it possible to make it work for react-native? I want to create a file for my mobile application.
Buffer is empty. The rest on fitWriter are the same with an example running on node directly.

```
 LOG  {"fitWriter": {"buffer": [], "crc": 42569, "definitionMap": Map {"record:position_lat*position_long*distance*speed*timestamp" => [Object]}, "devFieldTypes": Map {}, "lastTimeStamp": 1087661845, "localDefs": ["record:position_lat*position_long*distance*speed*timestamp", "record:position_lat*position_long*distance*speed*timestamp"], "nextLocalDef": 1, "offset": 169, "scratch": []}}
 ```
 
 Also added @craftzdog/react-native-buffer

**Comment by markw65** [comment]
I'm afraid I don't have an answer. I wrote it to use with a React app that I'm working on, but I've never used React-Native.

If you can set up a minimal repro, I can try to take a look.

**Comment by markw65** [comment]
My guess is that ArrayBuffer isn't working correctly in React-Native.

You can see that both `buffer` and `scratch` are empty in your log line, even though `scratch` is initialized as DataView over an 8 element ArrayBuffer, and never re-allocated.

But I'm not sure how you're producing that line. It almost looks like the result of `JSON.stringify(fitWriter)`, but that would report the DataView's as `{}` rather than `[]`. So the "empty" DataView's may just be an artifact of how you're converting the fitWriter to a string...

**Comment by RafaelCENG** [comment]
Thanks for the responses. I will try tommorow at work.
